# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Adapted from https://github.com/r-pkg-examples/rcpp-cpp11-usage

language: r
cache: packages

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      disable_homebrew: true
      r: oldrel
    - os: linux
      dist: trusty
      r: oldrel



## This is just a temporary fix -- should be addressed with CRAN submission
warnings_are_errors: false

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages:
      - gcc-8
      - g++-8
      - gfortran-8
      
env:
  global:
  - MAKEFLAGS="-j 2"
  - COMPILER=g++-8
  - CC=gcc-8
  - CXX=g++-8

before_install:
  - mkdir -p ~/.R && touch ~/.R/Makevars
  - VER=-8
  - echo "CC=gcc$(VER)"    >> ~/.R/Makevars
  - echo "CXX=g++$(VER)"   >> ~/.R/Makevars
  - echo "CXX1X=g++$(VER)" >> ~/.R/Makevars
  - echo "FC=gfortran$(VER)"       >> ~/.R/Makevars
  - echo "F77=gfortran$(VER)"      >> ~/.R/Makevars
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 60
  
notifications:
  email:
    on_success: never
    on_failure: never